### PR TITLE
Added the js files required for the proper functioning of bootstrap

### PR DESCRIPTION
**Pull request by AbreuY**
Many of the Bootstrap components require the use of JavaScript to function. Specifically, they require their own JavaScript plugins and Popper.

Bootstrap components requiring JavaScript:

- Alerts for dismissing
- Buttons for toggling states and checkbox/radio functionality
- Carousel for all slide behaviors, controls, and indicators
- Collapse for toggling visibility of content
- Dropdowns for displaying and positioning (also requires Popper)
- Modals for displaying, positioning, and scroll behavior
- Navbar for extending our Collapse plugin to implement responsive behavior
- Offcanvases for displaying, positioning, and scroll behavior
- Toasts for displaying and dismissing
- Tooltips and popovers for displaying and positioning (also requires Popper)
- Scrollspy for scroll behavior and navigation updates

### CODE REVIEW

**Comment by AbreuY** [comment]
Hi @alesanchezr, please review these changes.

**Comment by AbreuY** [comment]
Hi, @alesanchezr  
please review these changes. Thank you.

**Comment by AbreuY** [comment]
Hi @alesanchezr please review these changes. Thank you.

**Review by alesanchezr — APPROVED** [review]

**Comment by alesanchezr** [comment]
thank you!

**Pull request merged**
